#spring.application.name=api-gateway

server:
  port: 8406

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: BLOG-SERVICE
          uri: lb://BLOG-SERVICE
          predicates:
            - Path=/api/blog/**

        - id: COMMENT-SERVICE
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/api/comment**

        - id: LIKE-SERVICE
          uri: lb://LIKE-SERVICE
          predicates:
            - Path=/api/like/**

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm
